diermand-block: PURPUR_BLOCK
can-player-rename: true

naam:
  minimum-length: 3
  maximum-length: 16
  allow-colors: true
  blacklist:
    - ".nl"
    - "www."
    - "kanker"
    - "tyfus"
    - "kkr"
    - "kech"
    - "sukkel"
    - "homo"
    - "gay"
    - ".be"
    - ".com"
    - ".net"
    - ".ga"
    - ".tk"
    - "play."